### PR TITLE
+= pagefind

### PR DESCRIPTION
**Pull request by sebbASF**
Sample config

### CODE REVIEW

**Comment by bdelacretaz** [comment]
Is `npx` available on the Jenkins build?

**Comment by rlenferink** [comment]
This looks quite neat when tested locally! I updated the README with the steps I had to execute to get this working locally.

I checked [the Jenkins build](https://ci-builds.apache.org/job/Community%20Development/job/site/job/pagefind/2/console) for this branch and it seems that `npx` is not available:

```
+ npx -y pagefind --source /tmp/tmp.Gyx0fKCW5W/content
/home/jenkins/workspace/munity_Development_site_pagefind@tmp/durable-59bbcbc2/script.sh: 1: npx: not found
```

A solution I was thinking of: we could add a `Containerfile` (intentionally not called Dockerfile), add the required tooling there (`hugo`, `npx` etc.) and use that image for building the website in Jenkins, but also for users who want to do local testing.

**Comment by bdelacretaz** [comment]
You might also install a `pagefind` binary ( https://github.com/CloudCannon/pagefind/releases ) from the `Jenkinsfile`, similar to how Hugo is installed for this build? Pagefind installation instructions are at https://pagefind.app/docs/installation/

**Comment by bdelacretaz** [comment]
...and BTW it would be good to verify checksums when downloading external tools.

I've never done this in a Jenkinsfile myself but https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#verifysha256-verify-the-sha256-of-a-given-file has a suggestion , assuming that https://plugins.jenkins.io/pipeline-utility-steps/ are installed on our Jenkins services.

**Comment by rlenferink** [comment]
> I've raised INFRA-24405

To be honest: I don't like the idea of globally installed tooling.

Different projects are using different versions of Hugo (Celix uses 0.63.2, Jena uses 0.66.0, MINA 0.63.2, Directory uses Hugo, SIS, Nutch etc). What happens if we rely on version 0.111.3 and in quite some time another project asks INFRA to update to 1.0.0 (or another version which contains a breaking change).

IMO users (different projects) should install what they need themselves (either in a container or in a temporary path as we previously did in the Jenkinsfile). Our website isn't gonna fix itself if INFRA decides to update Hugo within period X. It is better to be in full control then instead of e.g. a build starting to fail (or worse: some side effect we don't directly see, e.g. a successful build but the build generating broken URLs).

(speaking from personal experience at `$work` that not pinning tooling versions is a path you don't want to take)

**Pull request merged**
