### PR TITLE
Proposed new layout of front page.

### PR DESCRIPTION
**Pull request by rbowen**

### CODE REVIEW

**Comment by rbowen** [comment]
You can see a screenshot here - https://boxofclue.com/community.a.o.2.png - if that's easier for you than attempting to stage this branch.

**Comment by bdelacretaz** [comment]
> ...if that's easier for you than attempting to stage this branch....

Note that if you name your branch `preview/...` in this repository it should be staged automatically.

**Comment by bdelacretaz** [comment]
...and +1 on the new layout, looks great to me! Assuming it works on smaller screens as well, I have not tested that.

**Comment by rbowen** [comment]
I've never actually gotten the preview/ thing working, although I know it's supposed to. :shrug:

**Comment by rbowen** [comment]
On smaller (eg phone) screens it becomes a single column of images.

**Comment by bdelacretaz** [comment]
FWIW, the preview is now at https://community-frontpage1106.staged.apache.org/

I have converted the new images to `webp` format for better performance, in commit 575eb782 on that branch, using `ffmpeg -i <image.jpg> <image.webp>

**Comment by rbowen** [comment]
Thanks. I've applied that change to my PR.

**Comment by rbowen** [comment]
I've made a number of changes based on commentary here and in Slack. Please have a look at the updated preview - https://community-frontpage1106.staged.apache.org/

**Comment by rbowen** [comment]
I'm taking the various reviews as approval to move forward with this. Please do feel free to revert if you disagree with this assessment.

**Pull request merged**
