### PR TITLE
Add Open Graph metadata for better previews in social media

### PR DESCRIPTION
**Pull request by turbaszek**
Hello,

This PR aims to add Open Graph metadata to improve rendering previews of ComDev site in social medias.

I'm not sure how to test it locally, but I based my work on:
https://gohugo.io/templates/internal/#open-graph
https://github.com/thingsym/hugo-theme-techdoc/blob/master/exampleSite/config.toml

Added photos are part of ACEU19 gallery:
https://photos.apachecon.com/picture.php?/395/category/1
https://photos.apachecon.com/picture.php?/253/category/1

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by bdelacretaz** [comment]
I built the site locally with these changes and the homepage has no difference with a build that does not have them.

I'm not familiar with OpenGraph and have only limited experience with Hugo but as per https://gohugo.io/templates/internal/ I tried the following change:

    diff --git a/layouts/_default/baseof.html b/layouts/_default/baseof.html
    index f7f5f49..ff7ebfe 100644
    --- a/layouts/_default/baseof.html
    +++ b/layouts/_default/baseof.html
    @@ -50,6 +50,7 @@
               margin-top:1em;
           }
       </style>
    +  {{ template "_internal/opengraph.html" . }}
     </head>
     
     <body>

And with this I see a number of `<meta>` elements on the homepage:

     <meta property="og:title" content="Apache Community Development - Welcome" />
    <meta property="og:description" content="The Community Development project creates and provides tools, processes, and advice to help open-source software projects improve their own community health." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://localhost:1313/" />
    <meta property="og:image" content="http://localhost:1313/images/aceu19_1.jpg"/>
    <meta property="og:site_name" content="Apache Community Development" />

So I suppose we should make this template change in addition to the changes in this PR, to include the OpenGraph metadata in the site pages? Or is there another way to access this new metadata that I'm missing?

**Review by bdelacretaz — APPROVED** [review]

**Comment by turbaszek** [comment]
> So I suppose we should make this template change in addition to the changes in this PR, to include the OpenGraph metadata in the site pages? Or is there another way to access this new metadata that I'm missing?

Seems I missed this part of documentation!  Looks good now:

**Comment by bdelacretaz** [comment]
>  Looks good now..

Out of curiosity, which tool are you using the check those previews?

**Comment by turbaszek** [comment]
Based on one SO thread I did this:
```
hugo server -D
lt --port 1313
```
The `lt` command is the [localtunnel](https://localtunnel.github.io/www/) command which works similar to ngrok. Then I check the generated url using https://www.opengraph.xyz

Simpler than I expected

**Comment by turbaszek** [comment]
@bdelacretaz do we wait for more approvals or we are good to merge this one?

**Comment by turbaszek** [comment]
Eventually pinging @markt-asf for opinion as this is somehow related to ASF branding

**Comment by bdelacretaz** [comment]
I'm fine with merging this and I don't think there's any trademarks impact as this is only adding metadata to the http://community.apache.org/ pages.

**Pull request merged**
